gui:
  nerdFontsVersion: "3"
disableStartupPopups: true
notARepository: quit
git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      colorArg: always
